import { Button, VerticalBox, StandardButton, StandardTableView, HorizontalBox, ScrollView } from "std-widgets.slint";

export component AuthorizationWindow inherits Window {
    callback authorization(string, string);
    VerticalBox {
        Text {
            text: "Введите логин и пароль";
        }

        VerticalLayout {
            Text {
                text: "Логин";
            }
            login_input := TextInput {}
        }

        VerticalLayout {
            Text {
                text: "Пароль";
            }
            password_input := TextInput {
                input_type: password;
            }
        }

        Button {
            text: "Авторизовтаься";
            clicked => {
                root.authorization(login_input.text, password_input.text);
            }
        }
    }
}

export component ErrorWindow inherits Dialog {
    in-out property <string> message: "";
    Text { text: "Ошибка: \{root.message}"; }
}

export component RegisterUserMenu inherits Window {
}

export component AdminMainMenu inherits Window {
    callback groups();
    callback specializaions();
    height: 500px;
    width: 215px;
    title: "Меню администратора";
    VerticalBox {
        Text { text: "Вы вошли как администратор"; }
        Button {
            height: 50px;
            width: 200px;
            text: "Специальности";
            clicked => {specializaions();}
        }
        Button {
            height: 50px;
            width: 200px;
            text: "Группы";
            clicked => {groups();}
        }
        Button {
            height: 50px;
            width: 200px;
            text: "Студенты";
            clicked => {groups();}
        }
        Button {
            height: 50px;
            width: 200px;
            text: "Предметы";
            clicked => {groups();}
        }
        Button {
            height: 50px;
            width: 200px;
            text: "Аккаунты студентов";
            clicked => {groups();}
        }
        Button {
            height: 50px;
            width: 200px;
            text: "Аккаунты преподавателей";
            clicked => {groups();}
        }
    }
}


export component DecanMainMenu inherits Window {
    height: 500px;
    width: 500px;
    title: "Меню сотрудника деканата";
}

export component TeacherMainMenu inherits Window {
    height: 500px;
    width: 500px;
    title: "Меню преподавателя";
}

export component StudentMainMenu inherits Window {
    in-out property <string> info;
    height: 500px;
    width: 500px;
    title: "Меню студента";
    VerticalBox {
        Text { text: "Вы вошли как \{info}"; }
    }
}

export component FullTableWindow inherits Window {
    callback export_to_excel();
    callback add_new();
    callback change_row(int);
    callback refresh();
    in-out property <[[StandardListViewItem]]> data: [];
    in-out property <[TableColumn]> columns: [];
    in-out property <string> window_title: "";
    title: window_title;
    min-height: 500px;
    HorizontalLayout {
        padding: 20px;
        spacing: 10px;
        Button {
            height: 25px;
            width: 100px;
            text: "Обновить";
            clicked => { refresh(); }
        }
        Button {
            height: 25px;
            width: 100px;
            text: "Изменить";
            clicked => { change_row(table.current-row); }
        }
        Button {
            height: 25px;
            width: 100px;
            text: "Добавить";
            clicked => { add_new(); }
        }
        Button {
            height: 25px;
            width: 200px;
            text: "Экспортировать в xlsx";
            clicked => { export_to_excel(); }
        }
    }
    ScrollView {
        table := StandardTableView {
            columns: root.columns;
            rows: root.data;
        }
    }
    
}

export component AddSpecialization inherits Window {
    callback ok(string, string);
    height: 150px;
    width: 500px;
    title: "Добавить специализацию";
    VerticalBox {
        Text {
            text: "Введите шифр";
        }
        cifr := TextInput {}
        Text { text: "Введите название специальности"; }
        name := TextInput {}
        Button {
            text: "ОК";
            clicked => {ok(cifr.text, name.text);}
        }
    }
}

export component ChangeSpecialization inherits Window {
    callback ok(string, string);
    callback delete();
    in-out property <string> cifr_value : "";
    in-out property <string> name_value : "";
    height: 200px;
    width: 500px;
    title: "Изменить специализацию";
    VerticalBox {
        Text {
            text: "Введите шифр";
        }
        cifr := TextInput { text: cifr_value; }
        Text { text: "Введите название специальности"; }
        name := TextInput { text: name_value; }
        Button {
            text: "ОК";
            clicked => {ok(cifr.text, name.text);}
        }
        Button {
            text: "Удалить специализацию";
            clicked => {delete();}
        }
    }
}